apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team3-booking-app
  namespace: team3-ns
spec:
  project: default
  source:
    repoURL: 'https://github.com/CSU-ITMO-2025-2/team3-booking-system.git'
    targetRevision: HEAD
    # где Helm-чарт
    path: k8s/charts/backend-service
    
    # Параметры для деплоя
    helm:
      parameters:
        - name: appName
          value: booking-service
  
  # Куда деплоить
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: team3-ns
  
  # Автосинхра 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true